# Generated by Django 5.1.6 on 2025-04-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(help_text='Phone number in format: +2348012345678', max_length=13),
        ),
    ]
