# Generated by Django 5.1.6 on 2025-04-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributionID', models.IntegerField()),
                ('flowRate1', models.FloatField(blank=True, null=True)),
                ('volume1', models.FloatField(blank=True, null=True)),
                ('flowRate2', models.FloatField(blank=True, null=True)),
                ('volume2', models.FloatField(blank=True, null=True)),
                ('flowRate3', models.FloatField(blank=True, null=True)),
                ('volume3', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
