# Generated by Django 5.1.6 on 2025-04-08 11:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50)),
                ('flowRate', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('created', api.models.FormattedDateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TokenHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50)),
                ('token_amount', models.DecimalField(decimal_places=2, help_text='Amount of tokens purchased', max_digits=10)),
                ('volume_limit', models.DecimalField(decimal_places=2, help_text='Total volume of water allocated (in liters)', max_digits=10)),
                ('volume_used', models.DecimalField(decimal_places=2, default=0, help_text='Volume of water consumed (in liters)', max_digits=10)),
                ('remaining_volume', models.DecimalField(decimal_places=2, help_text='Remaining volume of water (in liters)', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is currently active')),
                ('start_date', api.models.FormattedDateTimeField(auto_now_add=True)),
                ('last_updated', api.models.FormattedDateTimeField(auto_now_add=True, help_text='Last time token was recharged')),
                ('end_date', api.models.FormattedDateTimeField(blank=True, help_text='When the allocated volume was fully consumed', null=True)),
            ],
            options={
                'verbose_name_plural': 'Token History',
                'ordering': ['-start_date'],
            },
        ),
    ]
