# Generated by Django 5.1.6 on 2025-04-04 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowdata',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='flowdata',
            old_name='flowRate1',
            new_name='flowRate',
        ),
        migrations.RenameField(
            model_name='flowdata',
            old_name='flowRate2',
            new_name='volume',
        ),
        migrations.RemoveField(
            model_name='flowdata',
            name='flowRate3',
        ),
        migrations.RemoveField(
            model_name='flowdata',
            name='volume1',
        ),
        migrations.RemoveField(
            model_name='flowdata',
            name='volume2',
        ),
        migrations.RemoveField(
            model_name='flowdata',
            name='volume3',
        ),
        migrations.AddField(
            model_name='flowdata',
            name='sensor_id',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='flowdata',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
