# Generated by Django 5.1.6 on 2025-04-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_flowdata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowdata',
            name='distributionID',
        ),
        migrations.AlterField(
            model_name='flowdata',
            name='sensor_id',
            field=models.CharField(max_length=50),
        ),
    ]
