# Generated by Django 5.1.6 on 2025-04-07 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_flowdata_distributionid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50)),
                ('token_amount', models.DecimalField(decimal_places=2, help_text='Amount of tokens purchased', max_digits=10)),
                ('volume_limit', models.DecimalField(decimal_places=2, help_text='Total volume of water allocated (in liters)', max_digits=10)),
                ('volume_used', models.DecimalField(decimal_places=2, default=0, help_text='Volume of water consumed (in liters)', max_digits=10)),
                ('remaining_volume', models.DecimalField(decimal_places=2, help_text='Remaining volume of water (in liters)', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is currently active')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When the allocated volume was fully consumed', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Token History',
                'ordering': ['-start_date'],
            },
        ),
    ]
