# Generated by Django 5.1.6 on 2025-04-07 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tokenhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenhistory',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Last time token was recharged'),
            preserve_default=False,
        ),
    ]
