# Generated by Django 5.1.6 on 2025-04-07 23:02

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tokenhistory_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowdata',
            name='created',
            field=api.models.FormattedDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tokenhistory',
            name='end_date',
            field=api.models.FormattedDateTimeField(blank=True, help_text='When the allocated volume was fully consumed', null=True),
        ),
        migrations.AlterField(
            model_name='tokenhistory',
            name='last_updated',
            field=api.models.FormattedDateTimeField(auto_now_add=True, help_text='Last time token was recharged'),
        ),
        migrations.AlterField(
            model_name='tokenhistory',
            name='start_date',
            field=api.models.FormattedDateTimeField(auto_now_add=True),
        ),
    ]
